# Generated by Django 3.2.12 on 2022-04-12 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobilemarket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pmodel',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.SET_DEFAULT, to='mobilemarket.pmodel', verbose_name='型號'),
        ),
    ]
