# Generated by Django 3.2.12 on 2022-04-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='born_year',
            field=models.PositiveIntegerField(default=1960),
        ),
    ]
